### PR TITLE
Fix for #31 Version 6.1.8 does not initialize collections at the end of nesting data structures

### LINKED ISSUE #31: Version 6.1.8 does not initialize collections at the end of nesting data structures
There is a test that is supposed to verify the scenario, i.e. `shouldLimitTheNestingLevel_whenInRecursiveStructures`, but it was changed from:
```
        assertThat(actual.children().get(0))
            .as("On the 2nd level, the field should be initialized with empty list, i.e. end of nesting.")
            .isEqualTo(new NestedRecordThroughCollection(List.of()));
```
to:
```
        assertThat(actual.children().get(0))
            .as("On the 2nd level, the field should be initialized with empty list, i.e. end of nesting.")
            .isEqualTo(new NestedRecordThroughCollection(List.of()));
```

### PR DESCRIPTION
**Pull request by mjureczko**
Fix #31 (Version 6.1.8 does not initialize collections at the end of nesting data structures)

### CODE REVIEW

File: easy-random-core/src/main/java/org/jeasy/random/RecordFactory.java [hunk 1]
```diff
@@ -67,30 +67,26 @@ private <T> T createRandomRecord(Class<T> recordType, RandomizationContext conte
...
-                try {
-                    if (isRecord(type)) {
-                        randomValues[i] = easyRandom.doPopulateBean(type, context);
+
+        for (int i = 0; i < recordComponents.length; i++) {
+            context.pushStackItem(new RandomizationContextStackItem(recordType, null));
+            Class<?> type = recordComponents[i].getType();
+            try {
+                if (isRecord(type)) {
+                    if (context.hasExceededRandomizationDepth()) {
```
Comment (dvgaba) [inline easy-random-core/src/main/java/org/jeasy/random/RecordFactory.java:76]: Can we move this check outside of this if condition?

Comment (mjureczko) [reply easy-random-core/src/main/java/org/jeasy/random/RecordFactory.java]: `recordFieldPopulator.populateField` already had the logic, but as you pointed out it can be outside of this if the condition and then it is possible to remove it from `recordFieldPopulator.populateField` so that the `hasExceededRandomizationDepth` is checked only in one place for records.

Comment (mjureczko) [reply easy-random-core/src/main/java/org/jeasy/random/RecordFactory.java]: @dvgaba how about merging the change?

Comment (mjureczko) [reply easy-random-core/src/main/java/org/jeasy/random/RecordFactory.java]: @dvgba, could you let me know when I can expect a decision regarding the merging of this PR? Your response would be greatly appreciated.

Comment (mjureczko) [reply easy-random-core/src/main/java/org/jeasy/random/RecordFactory.java]: My perspective might be biased, but I would recommend making it the default approach. For the majority of cases, this choice might not have a significant impact since reaching the recursion limit without recursive data structures is rare. However, when working with such data, the prevailing guideline for production code is to employ empty collections rather than nulls. Production code factories create initialized collections, and algorithms — tested with data generated by easy-random — typically assume the absence of nulls. Therefore, I believe that in scenarios where this distinction matters, initializing the collections is more convenient.
